from Program.Aircraft import Aircraft
from Program.Car import Car
from Program.Boat import Boat

plain = Aircraft(1, "Boing", "77", 2008, 100, 10, 1000)
car = Car(2, "BMW", "X7", 2022, 80, 75)
boat = Boat(3, "qwe", "ewq", 2002, 100, 50)
print(plain.displayInfo())
print("------------")
print(plain.refuel(100))
print("------------")
print(plain.take_off())
print("------------")
print(plain.displayInfo())
print("------------")
print(plain.land())
print("------------")
print(plain.displayInfo())
print("------------")
print("------------")
print("------------")
print("------------")
print(car.acelerate(10))
print("------------")
print(car.displayInfo())
print("------------")
print(car.brake())
print("------------")
print(car.displayInfo())
print("------------")
print(car.refuel(100))
print("------------")
print(car.displayInfo())
print("------------")
print("------------")
print("------------")
print("------------")
print(boat.start_swimming())
print("------------")
print(boat.displayInfo())
print("------------")
print(boat.stop_swimming())
print("------------")
print(boat.displayInfo())
print("------------")
print(boat.refuel(30))
print("------------")
print(boat.displayInfo())